services:
  - type: web
    name: ait-search-engine
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: cd search_engine && python -m uvicorn app.backend.server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: PORT
        value: 10000